### ISSUE TITLE
Rewrite considerations

### ISSUE THREAD

**Issue by flavioheleno** [beluga-php/docker-php#49]
I've been thinking for a while now on rewriting this library from ground-up and replace any auto-generated code with hand crafted code, to avoid the issues we see with the changes and weird behaviors of JanePHP.

I'd like to gauge interest/opinions around this, specially from users who have been interacting by submitting issues and PRs.

Shall we start a new library or keep things as they are?

**Comment by flavioheleno** [comment]
cc @rodrigoaguilera @Rid

**Comment by rodrigoaguilera** [comment]
Is it really janePHP's problems or that the docker api spec doesn't reflect the actual api?
janePHP seems like a well-maintained project despite the problems it created for docker-php.

From my point of view dropping janePHP's "help" will also mean to keep up with future updates of the docker api manually. I'm thinking new enpdoints and parameters/options to existing endpoints. I don't have much experience with janePHP.

Another project on my radar is https://github.com/clue/reactphp-docker but I don't really need to do any async stuff and the seem to handcraft the API integration. The consequence is that they don't cover all the endpoints in the API. I think is one of the wins of docker-php.

Thanks for pinging for discussion.

**Comment by flavioheleno** [comment]
The thing with Jane is that every now and then they change how things are generated (compare the results of generated code throughout 7.x releases and you'll see that it changes quite a bit even though they are at the same major version), and that usually breaks signatures on docker-php (as it extends docker-php-api).

I haven't used all of the API to have a strong opinion/argument about it being or not the source of issues to be honest, so you could be 100% right that handcrafting the integration is a poor decision/choice.

Maybe automating/modernizing the whole thing and improving the test suite would be enough to make this more sustainable.

**Comment by Rid** [comment]
@flavioheleno Thanks for bringing up this important topic for discussion. I totally understand the frustration that comes with some of the issues and weird behaviours we've encountered while using JanePHP. The idea of rewriting the library with hand-crafted code is certainly tempting and could offer more control over the codebase.

However, I'd like to advocate for sticking with JanePHP for a couple of reasons:

**API Coverage**: JanePHP has the advantage of covering the entire API. I, personally, rely heavily on this wide range of API features, and replicating this in a new library could be a massive effort.

**Development Time**: Reaching feature parity with the current version would be a significant undertaking. The effort required to write, test, and maintain hand-crafted code for the entire API could be considerable and may divert our attention from other valuable tasks.

**Maintenance**: I'm committed to maintaining the current version and updating JanePHP when needed, which should mitigate some of the issues we've been experiencing.

While a rewrite might give us more control, it could also open the door to new bugs and require extensive testing to ensure we're not introducing new issues. I think it would be more efficient to fix the JanePHP issues as they come up, rather than undertaking the huge task of a complete rewrite.

**Comment by flavioheleno** [comment]
Thanks for chiming in @Rid!

I think the **API Coverage** topic is a concern for both you and @rodrigoaguilera, which was neglected by myself when thinking about the rewrite.

In terms of **Development Time** and **Maintenance**, you are 100% right that there is a lot more effort to write from scratch than trying to work with/around JanePHP, but I did consider this when I thought about the rewrite (probably too lightly though).

I'd say it's settled that we should keep working with what we have and look for ways to improve and modernize it.

I've given both of you write access to `beluga-php/*` so we can work together and make this happen.

I'll open a discussion on the organization so we can outline some plans moving forward.

Thank you both for all the effort and time you've put in helping out, it's very much appreciated! :)
